### ISSUE TITLE
Add S3 credentials to .travis.yml

### ISSUE THREAD

**Issue by knservis** [snowplow-incubator/snowplow-piinguin-relay#4]
can you please add the values:

```
AWS_KEY
AWS_SECRET
```

in https://github.com/snowplow-incubator/snowplow-piinguin-relay/blob/fa9ff6f4bb405219c94ab24a1246308f9fa12ed1/.travis.yml#L76-L78

**Comment by alexanderdean** [comment]
Per https://github.com/snowplow-incubator/snowplow-indicative-relay/issues/2, I will add:

- `AWS_DEPLOY_ACCESS_KEY_ID`
- `AWS_DEPLOY_SECRET_ACCESS_KEY`

**Comment by knservis** [comment]
Thanks!
